---

- name: Retrieve latest release information
  ansible.builtin.uri:
    url: https://api.github.com/repos/charmbracelet/gum/releases/latest
    return_content: true
  register: project_info
  changed_when: false
  check_mode: false

- name: Override version to setup if latest
  ansible.builtin.set_fact:
    gum_version: "{{ project_info.content | from_json | json_query('tag_name') | replace('v', '') }}"
  changed_when: false
  check_mode: false
  when:
    - gum_version == "latest"

- name: Check gum version
  become: false
  ansible.builtin.shell: "set -o pipefail && gum -v  | cut -d' ' -f3 | sed 's#v##g'"
  args:
    executable: /bin/bash
  register: gum_version_client_installed
  changed_when: false
  failed_when: false
  check_mode: false

- name: Check gum version # noqa command-instead-of-shell
  ansible.builtin.shell: '/bin/true'
  changed_when: gum_version_client_installed.stdout != gum_version
  check_mode: false

# - debug:
#     var: gum_version_client_installed.stdout

- name: Install gum
  when:
    - not ansible_check_mode
    - gum_version != gum_version_client_installed.stdout
  block:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ gum_tmp_directory }}/{{ gum_os }}-{{ gum_arch }}/"
        state: directory
        mode: '0755'

    - name: Download and unarchive gum
      ansible.builtin.unarchive:
        src: "https://github.com/charmbracelet/gum/releases/download/v{{ gum_version }}/gum_{{ gum_version }}_{{ gum_os }}_{{ gum_arch }}.tar.gz"
        dest: "{{ gum_tmp_directory }}/{{ gum_os }}-{{ gum_arch }}/"
        remote_src: true
        mode: "0755"

    - name: Copy file with owner and permissions 2
      ansible.builtin.copy:
        src: "{{ gum_tmp_directory }}/{{ gum_os }}-{{ gum_arch }}/gum_{{ gum_version }}_{{ gum_os }}_{{ gum_arch }}/gum"
        dest: "{{ gum_bin_path }}/gum"
        mode: '0755'
        remote_src: true

    - name: Clean temporary directory
      ansible.builtin.file:
        state: absent
        path: "{{ gum_tmp_directory }}/{{ gum_os }}-{{ gum_arch }}"
